'use client';
import {useEffect,useState} from 'react';
const initial={smartGoal:'',currentAction:'',estimatedMinutes:0,completionCriteria:'',completed:[]};
export default function Home(){const [goal,setGoal]=useState('');const [j,setJ]=useState(initial);const [loading,setLoading]=useState(false);const [obstacle,setObstacle]=useState('');const [showStuck,setShowStuck]=useState(false);const [flash,setFlash]=useState('');
useEffect(()=>{try{const s=localStorage.getItem('bitepath');if(s)setJ(JSON.parse(s))}catch{}},[]); useEffect(()=>{if(j.smartGoal)localStorage.setItem('bitepath',JSON.stringify(j))},[j]);
async function call(url,body){setLoading(true);setFlash('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Something went wrong');return d}catch(e){setFlash(e.message)}finally{setLoading(false)}}
async function start(){if(!goal.trim())return;const d=await call('/api/goal',{goal});if(d)setJ({...d,completed:[]})}
async function done(){const completed=[...j.completed,j.currentAction];setFlash('Path cleared.');const d=await call('/api/next',{smartGoal:j.smartGoal,completed});if(d)setJ({...j,...d,completed})}
async function smaller(){const d=await call('/api/smaller',{action:j.currentAction});if(d)setJ({...j,...d})}
async function stuck(){if(!obstacle.trim())return;const d=await call('/api/stuck',{smartGoal:j.smartGoal,action:j.currentAction,obstacle});if(d){setJ({...j,...d});setShowStuck(false);setObstacle('');setFlash(d.encouragement)}}
function reset(){localStorage.removeItem('bitepath');setJ(initial);setGoal('')}
if(!j.smartGoal)return <main className="forest"><section className="hero"><div className="lantern">✦</div><p className="eyebrow">BITEPATH</p><h1>What do you want<br/>to accomplish?</h1><p className="sub">Don't worry about how. Just tell us where you want to go.</p><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="I want to…"/><button onClick={start} disabled={loading}>{loading?'Lighting the path…':'Start My Journey →'}</button><p className="motto">One flashlight. One path. One bite at a time.</p></section></main>;
return <main className="forest"><section className="game"><header><div><p className="eyebrow">YOUR DESTINATION</p><h2>{j.smartGoal}</h2></div><button className="ghost" onClick={reset}>New journey</button></header><div className="trail">{j.completed.slice(-4).map((_,i)=><span className="node done" key={i}>✓</span>)}<span className="line"/><span className="node you">✦</span><span className="line dim"/><span className="node locked">?</span><span className="fog">•••</span></div><article className="card"><p className="eyebrow">YOUR NEXT BITE</p><h1>{j.currentAction}</h1><div className="meta"><span>◷ {j.estimatedMinutes} min</span><span>✓ Done when: {j.completionCriteria}</span></div><button className="donebtn" onClick={done} disabled={loading}>{loading?'…':'I DID IT ✓'}</button><div className="actions"><button onClick={smaller} disabled={loading}>Make this smaller</button><button onClick={()=>setShowStuck(!showStuck)}>I'm stuck</button></div>{showStuck&&<div className="stuck"><input value={obstacle} onChange={e=>setObstacle(e.target.value)} placeholder="What's stopping you?"/><button onClick={stuck}>Help me move</button></div>}</article>{flash&&<p className="flash">{flash}</p>}<p className="steps">{j.completed.length} steps behind you. Only this one matters now.</p></section></main>}
